#!/bin/bash

if [[ -d dist ]]; then
  rm -rf dist;
fi

mkdir -p ./dist/containers ./dist/components;

#./node_modules/babel-cli/bin/babel.js ./src/ --compact true | ./node_modules/uglify-js/bin/uglifyjs -o ./dist/index.js;

scripts=`find ./src/ -name "*.js"`;
arrScripts=(${scripts//'\n'/});
for script in "${arrScripts[@]}"; do
  scriptName=`perl -pe "s/\.\/src\///g" <<< $script`;
  echo $scriptName;
  ./node_modules/babel-cli/bin/babel.js $script --compact true | ./node_modules/uglify-js/bin/uglifyjs -o ./dist/$scriptName;
done;
